CREATE TABLE  "ROLE" 
   (	"ID" NUMBER(10,0), 
	"TITLE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ACCOUNT" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LOGIN" VARCHAR2(20) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PRIORITY" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "ACCOUNT_EML" CHECK (regexp_like ("EMAIL", '[a-zA-Z0-9._%-]+@[a-zA-Z0-9._%-]+\.[a-zA-Z]{2,4}') ) ENABLE,
	 CONSTRAINT "ROLE_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES  "ROLE" ("ID") ENABLE
   )
/
CREATE TABLE  "RESOURCES" 
   (	"ID" NUMBER(10,0), 
	"TITLE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "RESOURCES_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "JOURNAL" 
   (	"ID" NUMBER(10,0), 
	"BEGIN_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"END_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"RESOURCE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "JOURNAL_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "ACCOUNT_FK" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES  "ACCOUNT" ("ID") ENABLE, 
	 CONSTRAINT "RESOURCE_FK" FOREIGN KEY ("RESOURCE_ID")
	  REFERENCES  "RESOURCES" ("ID") ENABLE
   )
/
CREATE TABLE  "RES_ROLE" 
   (	"ID" NUMBER(10,0), 
	"RES_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "RES_ROLE_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "RR_RESOURCE_FK" FOREIGN KEY ("RES_ID")
	  REFERENCES  "RESOURCES" ("ID") ENABLE, 
	 CONSTRAINT "RR_ROLE_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES  "ROLE" ("ID") ENABLE
   )
/
 CREATE SEQUENCE   "ACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "JOURNAL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "RESOURCES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "RES_ROLE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ROLE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "ACCOUNT_TRG" 
BEFORE
insert on "ACCOUNT"
for each row
begin
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT ACCOUNT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
  NULL;
end;
/
ALTER TRIGGER  "ACCOUNT_TRG" ENABLE
/
CREATE OR REPLACE TRIGGER  "JOURNAL_TRG" 
BEFORE
insert on "JOURNAL"
for each row
begin
<<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT JOURNAL_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
  NULL;
end;
/
ALTER TRIGGER  "JOURNAL_TRG" ENABLE
/
CREATE OR REPLACE TRIGGER  "RESOURCES_TRG" 
BEFORE
insert on "RESOURCES"
for each row
begin
<<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT RESOURCES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
  NULL;
end;
/
ALTER TRIGGER  "RESOURCES_TRG" ENABLE
/
CREATE OR REPLACE TRIGGER  "RES_ROLE_TRG" 
BEFORE
insert on "RES_ROLE"
for each row
begin
<<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT RES_ROLE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
  NULL;
end;
/
ALTER TRIGGER  "RES_ROLE_TRG" ENABLE
/
CREATE OR REPLACE TRIGGER  "ROLE_TRG" 
BEFORE
insert on "ROLE"
for each row
begin
<<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT ROLE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
  NULL;
end;
/
ALTER TRIGGER  "ROLE_TRG" ENABLE
/
CREATE OR REPLACE FORCE VIEW  "ACC_RES_VIEW" ("PRIORITY", "ID", "NAME", "LOGIN", "PASSWORD", "ROLE_TITLE", "RES_TITLE") AS 
  select	 "ACCOUNT"."PRIORITY" as "PRIORITY",
	 "ACCOUNT"."ID" as "ID",
	 "ACCOUNT"."NAME" as "NAME",
	 "ACCOUNT"."LOGIN" as "LOGIN",
	 "ACCOUNT"."PASSWORD" as "PASSWORD",
	 "ROLE"."TITLE" as "ROLE_TITLE",
	 "RESOURCES"."TITLE" as "RES_TITLE" 
 from	 "ACCOUNT" "ACCOUNT",
	 "RES_ROLE" "RES_ROLE",
	 "RESOURCES" "RESOURCES",
	 "ROLE" "ROLE" 
 where   "RES_ROLE"."RES_ID"="RESOURCES"."ID"
 and	 "RES_ROLE"."ROLE_ID"="ROLE"."ID"
 and	 "ACCOUNT"."ROLE_ID"="ROLE"."ID"
order by ACCOUNT.PRIORITY ASC
/
CREATE OR REPLACE FORCE VIEW  "RES_ROLE_VIEW" ("ID", "ROLE_TITLE", "RES_TITLE") AS 
  select	 "RES_ROLE"."ID" as "ID",
	 "ROLE"."TITLE" as "ROLE_TITLE",
	 "RESOURCES"."TITLE" as "RES_TITLE" 
 from	 "RES_ROLE" "RES_ROLE",
	 "RESOURCES" "RESOURCES",
	 "ROLE" "ROLE" 
 where   "RES_ROLE"."RES_ID"="RESOURCES"."ID"
 and	 "RES_ROLE"."ROLE_ID"="ROLE"."ID"
order by RES_ROLE.ID ASC
/