DROP TRIGGER  "RES_ROLE_TRG"
/
DROP TRIGGER  "JOURNAL_TRG"
/
DROP TRIGGER  "RESOURCES_TRG"
/
DROP TRIGGER  "ACCOUNT_TRG"
/
DROP TRIGGER  "ROLE_TRG"
/
DROP SEQUENCE   "RES_ROLE_SEQ"
/
DROP SEQUENCE   "JOURNAL_SEQ"
/
DROP SEQUENCE   "RESOURCES_SEQ"
/
DROP SEQUENCE   "ACCOUNT_SEQ"
/
DROP SEQUENCE   "ROLE_SEQ"
/
DROP VIEW  "ACC_RES_VIEW"
/
DROP VIEW  "RES_ROLE_VIEW"
/
DROP TABLE  "RES_ROLE" 
/
DROP TABLE  "JOURNAL" 
/
DROP TABLE  "RESOURCES" 
/
DROP TABLE  "ACCOUNT" 
/ 
DROP TABLE  "ROLE" 
/